### ISSUE TITLE
Define and configure the smtp setup

### ISSUE THREAD

**Issue by colorfield** [drupal-celebrations/celebrate-drupal-9#12]
Currently, it is not possible to send mail.
We should figure out if this can be delegated to the Platform.sh infrastructure or if we want to make use a transactional service like Sendgrid.

- [x] Check if this can be delegated to the Platform infrastructure
- [ ] Check pricing policy of transactional services (Sendgrid, Mailgun, Mandrill, ...)
- [ ] Figure out if we want to make use of html mail
- [ ] Setup SMTP / Swiftmailer

**Comment by miromichalicka** [comment]
Docs: https://docs.platform.sh/development/email.html

**Comment by robertDouglass** [comment]
https://console.platform.sh/accounts-partners/5o5646iqitt5m/master/settings

There's a setting there to turn outgoing mails on.

**Comment by colorfield** [comment]
Now that we have the celebratedrupal.org domain + outgoing mails enabled, they are working properly. For html email or further configuration we could still open a follow up.
