### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#14]
Currently we use the _new_ default Drupal logo but it needs a class to set the width. Also, as it is blue, the current header is blue so we'll need to adapt one of the other so the logo stands out.

- [x] Logo is visible
- [x] Add width class
- [x] Change logo from blue version or change header from blue background
- [x] Ensure a11y is met (colours)

**Comment by miromichalicka** [comment]
Seems to be done
