### ISSUE TITLE
 Homepage hero is styled

### ISSUE THREAD

**Issue by zsofimajor** [drupal-celebrations/celebrate-drupal-9#21]
Hero area is styled, the navigation looks like on the design. 

The hero image should have an overlay, and the text color should be changed so it is easy to read.

**Comment by zsofimajor** [comment]
@dan2k3k4 do we want to keep this open if the design comes together or just close it?

**Comment by dan2k3k4** [comment]
I think we can close it, the idea was just to make sure the style is "good enough" for now. When we define an improved style then we can be more detailed with a follow-up issue
