### ISSUE TITLE
User fields

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#3]
I should be able to register a new user account with the following fields:

- [x] Username
- [x] Password
- [x] Email
- [x] Drupal.org username (optional, prefix: https://www.drupal.org/u/ )
- [x] Twitter username (optional, prefix: https://twitter.com/ )
- [ ] Timezone (maybe optional?)
- [ ] Country

**Comment by miromichalicka** [comment]
@dan2k3k4 prefixes should be used during rendering or do you mean default value / placeholder?

**Comment by dan2k3k4** [comment]
@miromichalicka I think I meant placeholder 😄 and we would render out the URL correctly (with logo etc.) on Frontend
