### ISSUE TITLE
Generalize image and video teasers and style them

### ISSUE THREAD

**Issue by colorfield** [drupal-celebrations/celebrate-drupal-9#35]
Here is the current status of video teasers
![Screenshot 2020-05-24 at 13 52 19](https://user-images.githubusercontent.com/525003/82753431-e12a8600-9dc5-11ea-9f2a-48918e154e25.png)

Proposed tasks

- [ ] Set responsive image style format based on https://docs.google.com/spreadsheets/d/1ysgdP5L-OOEfgiRgygiAmj06Ayr3m-wap7viOKejI54/edit#gid=0
- [ ] Sticky footer for author information (username, country, twitter/drupal icons)
- [ ] Title line height (see e.g. first element)
- [ ] Possibly different styling for user name and country
- [ ] Then it might be possible to generalize the teasers for videos

**Comment by dan2k3k4** [comment]
I think this is done @colorfield ? I mean we can improve things but perhaps let's create smaller issues for those

**Comment by colorfield** [comment]
Hi @dan2k3k4 yes most of these tasks are implemented or outdated (e.g. title) so we could fix the sticky footer https://github.com/drupal-celebrations/celebrate-drupal-9/pull/70 then close and open follow ups if needed.
