### ISSUE TITLE
Group facets filters

### ISSUE THREAD

**Issue by colorfield** [drupal-celebrations/celebrate-drupal-9#38]
Filters for videos and images (possible filters: category, country #37, celebration) are in the content region and there is no way to group/style them easily and thus make use of e.g. flex.

There is an investigation to make use of layout builder #36 but for the mvp we could start with a more simple approach (e.g. region or possibly https://www.drupal.org/project/facets_block)

**Comment by colorfield** [comment]
Facets block solves this, patch for D9 compatibility https://www.drupal.org/project/facets_block/issues/3142353, waiting for maintainer feedback

**Comment by miromichalicka** [comment]
we can use https://www.drupal.org/project/facets/issues/3073444 and that would also solve #36

**Comment by colorfield** [comment]
awesome! thanks @miromichalicka
