### ISSUE TITLE
Add a new Video

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#4]
As an "Authenticated" user I should be able to create a new Video which stores as a Draft, so that the "Content Moderators" can review and publish it.

- [x] Video should contain: Title
- [x] Video URL for YouTube, Vimeo

**Comment by miromichalicka** [comment]
`Videos can be played in the container or fullscreen` is imho more about provider's options, isn't it?

**Comment by dan2k3k4** [comment]
@miromichalicka yeah, agreed. I think whatever YouTube/Vimeo does for the media integration is probably good enough... although it would be nice to have the same "styling" overlay. I suppose that could be in a separate follow-up issue though.

**Comment by zsofimajor** [comment]
I removed the styling related tasks and moved them into https://github.com/drupal-celebrations/celebrate-drupal-9/issues/25

**Comment by miromichalicka** [comment]
Then I'm closing this one as all required work will be done in #25
