### ISSUE TITLE
Create the 'meet the team' display

### ISSUE THREAD

**Issue by colorfield** [drupal-celebrations/celebrate-drupal-9#42]
Mockup for the team of volunteers
https://balsamiq.cloud/sx3yk94/pdoh4q2/rE3FE

Favour a content type, as not every volunteer might have a Drupal user account so we shouldn't rely on the user entity for that. Also it prevents to deal with form modes (default/volunteer user profile).

- [x] Create a Volunteer content type
- [x] The title is used as the name field (first and last names are limitative / does not cover every case, so better to have a single field)
- [x] The existing description field can be used
- [x] Create the Drupal.org / Twitter account fields based on what is done for the user entity
- [x] Make use of Media image for the picture
- [x] Create a block display view that can be used as a paragraph embedded view
- [x] Alphabetical sort ascending based on title
- [x] Teaser view mode is set and styled
- [ ] Possibly use rabbit hole for the full view mode (page) - see https://www.drupal.org/project/rabbit_hole/issues/3091139

**Comment by dan2k3k4** [comment]
Content type could be called `Volunteer` to highlight that we're all volunteers? but also fine with `Team Member`

Node Title could be the name, but I suppose it could also be the pseudo-name of the person if they want to keep their privacy.

Description 👍 I presume it's a text long field, maybe it supports some bold/italic/links too? so team members could promote other things they do.

User entity, we _could_ pull the drupal.org/twitter info via entity reference of user but then we can be blocked on having to create the user first.

View -> yeah, sorted by name (node title) ascending, and display all.

Rabbit hole sure 👍 sounds good, thanks!

**Comment by colorfield** [comment]
Thanks!

Thought about other team members types, e.g. moderators - also volunteer though :) going for your proposal. 

Yes description is a long formatted text.

True for the user reference, but yes perhaps we will create the volunteers content for other users. We could keep it simple for now (fields on the CT) and maybe improve later.

**Comment by dan2k3k4** [comment]
Mmm I guess we could differentiate types of volunteers with a field and taxonomy term entity reference? As I assume the end-result would most likely always be the same "content" (who is this person, an image, a short description, and their social links).

**Comment by colorfield** [comment]
Yes we could introduce a type / discuss this on the next meeting.
