### ISSUE TITLE
Add 'Drupal CoC' to agreement for content upload

### ISSUE THREAD

**Issue by zsofimajor** [drupal-celebrations/celebrate-drupal-9#47]
Todo:
- [x] Add COC field to Event CT

Each 'Add content' page should have a checkbox for complying with the Drupal CoC.

This text should be:

My uploaded content complies with the Drupal Code of Conduct (https://www.drupal.org/dcoc).

This checkbox must be required in order to be able to upload the content.

**Comment by miromichalicka** [comment]
@zsofimajor just note - I didn't add the checkbox to Events because of text incompatibility, so if you can compose text for that, I'll add it.

**Comment by zsofimajor** [comment]
The event I'm hosting complies with the Drupal Code of Conduct (https://www.drupal.org/dcoc).

**Comment by zsofimajor** [comment]
@miromichalicka text added ^^
