### ISSUE TITLE
Add a new Image

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#5]
As an "Authenticated" user, I should be able to add a new Image node.

The node would then be saved into Draft state, so that the "Content Moderators" can review and publish it.

Images can be grouped into different categories for different events such as:
- Baking (Drupal 9 logo, or similar)
- Selfies (e.g. "This is what a Drupal developer looks like")
- Misc/Other (e.g. landscapes from around the world from the perspective of a Drupal developer).

In order to achieve the above, we need the following fields:

- [x] Image (media bundle... perhaps private images and per-user "media library")
- [x] Category (taxonomy term to relate to Baking, Selfies etc.)
- [x] Description (plain long-text, perhaps to allow people to write a one or two sentence about the image?)

Further thoughts, if we have Baking - we could have a "Recipes" field or content type?

**Comment by zsofimajor** [comment]
I think the description should be enough. Question (also to @colorfield (since you mentioned to create mockup). How will the description show? 

Also - do we want to allow users to add new taxonomy terms or we want to create a few ahead?

**Comment by miromichalicka** [comment]
Description field is added in dfa30b8

**Comment by colorfield** [comment]
@zsofimajor about the description, here is an example for
- the teasers: https://balsamiq.cloud/sx3yk94/pdoh4q2/r2278
- the detail (still discussing the overlay for accessibility but doesn't influence the rest): https://balsamiq.cloud/sx3yk94/pdoh4q2/r4B24

For the taxonomy terms (e.g. category), my understanding is that they will be created beforehand by moderators/admins and not on the fly (to prevent duplicates + set a color).

**Comment by zsofimajor** [comment]
i think we can consider this done
