### ISSUE TITLE
Redirect volunteer detail page to the about page.

### ISSUE THREAD

**Issue by colorfield** [drupal-celebrations/celebrate-drupal-9#53]
The volunteer detail page is unstyled and it does not really make sense to access it.

**Proposed resolution**
Implement an event subscriber that redirects to the about page (as a replacement of the original rabbit hole implementation that was proposed, as this module does not seem to be D9 ready yet).

**Comment by zsofimajor** [comment]
i don't think it's needed. It is nice to have us there, but very low prio.

**Comment by colorfield** [comment]
Has been done yesterday with https://github.com/drupal-celebrations/celebrate-drupal-9/commit/112f3cde0109c2b26cac2faa380bfcc87199cdb0 we could open a new issue if we want a detail page / style it. Minor, but so we will not stumble on unstyled pages via search engines.
