### ISSUE TITLE
Add Druplicon as favicon

### ISSUE THREAD

**Issue by zsofimajor** [drupal-celebrations/celebrate-drupal-9#58]
Please change the favicon to Druplicon.

**Comment by zsofimajor** [comment]
Attached the druplicon.
![druplicon](https://user-images.githubusercontent.com/4191750/83117103-f3116f00-a0cc-11ea-8c7b-8eefc1436402.png)

**Comment by dan2k3k4** [comment]
Thanks, I had to generate favicons from the above image. I then just put all of them (including `site.manifest` into the `web/themes/custom/drupal_celebrations` theme).

You can test if the favicon works and looks good for you.

**Comment by zsofimajor** [comment]
yes
