### ISSUE TITLE
Video Overview

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#6]
As an anonymous or authenticated user I should be able to view all published videos (sorted by date of creation desc).

Display should contain a card-view of each video with all information:
- [x] Video
- [x] Author name
- [x] Author location
- [x] Authors' Twitter/d.org if they have
- [x] add description field to image and video nodes
- [x] possibly add helper to get the category/color for the theme - follow up #32 
- [x] initial styling of image and video cards / refactor a bit twig to group as components
- [x] configure search api and facets index 
- [x] add icons on the user and twitter formatters
- [x] oEmbed thumbnail formatter for media video

Remaining tasks: possibly split in separate issues?
- ajax pager instead of load more (more accessible) --> #40
- filter (1) facet is a block, alignment and grouping with other blocks (facets) could be in a dedicated region or possibly by making use of layout builder in a more flexible approach --> #38, #36 

**Grouped in #35**

- responsive image styles (2) see https://docs.google.com/spreadsheets/d/1ysgdP5L-OOEfgiRgygiAmj06Ayr3m-wap7viOKejI54/edit#gid=0
- title line height (3)
- vertical alignment when 2 teasers have different height (4)

![Screenshot 2020-05-24 at 01 57 18](https://user-images.githubusercontent.com/525003/82742814-ca067c80-9d62-11ea-8c3f-e8fd8696b6df.png)

- remove cc license field for images --> #39 
- fix search api deprecated function --> #34
- contrast color --> #32

**Comment by colorfield** [comment]
As discussed on Slack let's create another issue for the vote and discuss the solution (Flag or Voting api) so it does not become a blocker for the mvp

**Comment by dan2k3k4** [comment]
and sorting for now will be just based on node content creation date descending

**Comment by colorfield** [comment]
Updated AC's and created #28 with low prio

**Comment by colorfield** [comment]
Closing as all remaining tasks have now sub issues
