### ISSUE TITLE
Add the repo link to the footer?

### ISSUE THREAD

**Issue by ranqiangjun** [drupal-celebrations/celebrate-drupal-9#60]
If someone new wants to contribute to this project, adding a link of this repo to the page might help to lead them here.

Add we can add contributors here to a page similar to https://drupalconsole.com/contributors if necessary.

Contributors and team are different slightly.

**Comment by dan2k3k4** [comment]
Ohh thanks @jungleran!

I have just added a link to this repository in the Footer menu as it was low effort.

We can look into improving it in the future (e.g. to list contributors, and switch to SVG icons).

Does that satisfy this feature request for you?

**Comment by ranqiangjun** [comment]
Sure :) thanks for your quick response!

**Comment by ranqiangjun** [comment]
And one concern that should this repo be renamed before being linked? As I read that this repo and the site celebratedrupal.org  will be used for future release as well.

For example: rename `celebrate-drupal-9` to `celebrate-drupal`

**Comment by dan2k3k4** [comment]
Yeah, as noted in Slack - we plan to rename just need to wait a bit as it's low priority and it may require tweaking things on platform.sh as well as informing the contributors to the project 😄, but thanks for the note!

Closing this issue as it is considered done.
