### ISSUE TITLE
Image on detail page should not be cut off

### ISSUE THREAD

**Issue by zsofimajor** [drupal-celebrations/celebrate-drupal-9#61]
The image is cut into square ratio on its node page: https://celebratedrupal.org/image/foodie-goods/are-you-also-preparing-cake

This should not be cut, should display the image in right ratio, the width should be kept only.

**Comment by dan2k3k4** [comment]
Did the changes on prod and exported the config to code and redeployed

**Comment by zsofimajor** [comment]
looks good
