### ISSUE TITLE
I'm able to add other users' media to my own posts

### ISSUE THREAD

**Issue by geerlingguy** [drupal-celebrations/celebrate-drupal-9#64]
**Describe the bug**

I created a user account, added a video, and then when I went to add media, I found that I could add a video without having to log in.

**To Reproduce**

1. Log in
2. Go to https://celebratedrupal.org/node/add/video
3. Click 'Add Media'
4. See that you can add other users' media

**Expected behavior**

I would expect to only be able to add my own media, otherwise I could impersonate other users who have uploaded their own.

**Screenshots**

<img width="1076" alt="Screen Shot 2020-05-28 at 8 28 26 PM" src="https://user-images.githubusercontent.com/481677/83211181-0dc20300-a122-11ea-822c-8683d0163ace.png">

**Additional context**

N/A

**Comment by dan2k3k4** [comment]
Eek, thanks for submitting. I believe it was working locally but we made some changes before go-live and I guess we skipped on testing this content type.

Looking into resolving it now.

**Comment by dan2k3k4** [comment]
Hi @geerlingguy, it looks like this was coming from `honeypot` module... that was added just before go-live 🙈

I've changed the settings from protecting all forms to just the anonymous facing forms.

Could you re-test and let me know if everything works for you now?

**Comment by geerlingguy** [comment]
Haha, I know the maintainer of that module! I'll retest later today.

**Comment by geerlingguy** [comment]
@dan2k3k4 - I'm now seeing _two_ media items from others available that I can add to my own nodes:

<img width="1280" alt="Screen Shot 2020-05-29 at 8 08 12 AM" src="https://user-images.githubusercontent.com/481677/83263099-accb1700-a183-11ea-8914-7deeeca06a91.png">

Permissions and media are not fun to mess with!

**Comment by dan2k3k4** [comment]
@geerlingguy yep the Media Library does not seem to have an easy solution to prevent seeing everyones images/videos.

I tried to look into this with [oknate](drupal.org/u/oknate), and I scaffolded out a small module: [custom/current_user_else_all)[https://github.com/drupal-celebrations/celebrate-drupal-9/blob/master/web/modules/custom/current_user_else_all/current_user_else_all.info.yml]

But for some reason adding a new contextual filter to Media Library view caused other issues.

Also clicking between "Grid" and "Table" caused the `all` default value to be added to show all values...
