### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#9]
- [x] Users can register
- [ ] GDPR?
- [x] Users can login if they have an account
- [x] Registration page is styled
- [x] Login page is styled

**Comment by zsofimajor** [comment]
Question: who can tell us what to do with GDPR?

**Comment by dan2k3k4** [comment]
I can reach out to some people in Amazee Metrics.

I'm not sure if we need anything related to GDPR - since I don't have Google Analytics (or any analytics) on the site but we do use Youtube which comes with it's own embedded iframe - so we would need to mention that somewhere.

**Comment by dan2k3k4** [comment]
I'll create a follow-up for checking GDPR.
